try{function initMap(){const uluru={lat:46.480661529216896,lng:30.73622725124049};const map=new google.maps.Map(document.getElementById("gmap"),{mapId:"707e2dbaeb3845cb",zoom:17,center:uluru,});const marker=new google.maps.Marker({position:uluru,map:map,})}
window.initMap=initMap}catch(e){console.log("Error in block:");console.log("GMaps");console.log(e)}
try{window.addEventListener('scroll',scrollDetection);function scrollDetection(){try{isLocked=scrollController.isLocked}catch(e){isLocked=!1}
if(!isLocked){try{onTopHeaderСhecking()}catch(e){console.log(e)}
try{toTopBtnHide()}catch(e){console.log(e)}
try{closeMenuOnSkroll()}catch(e){console.log(e)}
try{}catch(e){console.log(e)}}}}catch(e){console.log("Error in block:");console.log("Skroll events");console.log(e)}
const scrollController={isLocked:!1,scrollPosition:0,scrollbarWidth:window.innerWidth-document.body.offsetWidth,fixedElements:document.querySelectorAll('._fixed-fix'),disabledScroll(){scrollController.isLocked=!0;scrollController.scrollPosition=window.scrollY;this.scrollbarWidth=window.innerWidth-document.body.offsetWidth;document.documentElement.style.skrollBehavior='unset';document.body.style.cssText=`
      overflow: hidden;
      position: fixed;
      top: -${scrollController.scrollPosition}px;
      left: 0;
      height: 100vh;
      width: 100vw;
      padding-right: ${this.scrollbarWidth}px;
      `;this.fixedElements.forEach((element)=>{element.style.marginRight=`${this.scrollbarWidth}px`})},enabledScroll(){document.body.style.cssText=``;window.scroll({top:scrollController.scrollPosition})
document.documentElement.style.skrollBehavior='';scrollController.isLocked=!1;this.fixedElements.forEach((element)=>{element.style.marginRight='0'})},}
try{const iconMenu=document.querySelector('.menu__icon');const menuBody=document.querySelector('.menu__body');const iconMenuSoc=document.querySelector('.menu-soc__icon');const menuSocBody=document.querySelector('.menu-soc__body');if(iconMenu){iconMenu.addEventListener("click",function(e){iconMenuSoc.classList.remove('_active');menuSocBody.classList.remove('_active');iconMenu.classList.toggle('_active');menuBody.classList.toggle('_active')})};if(iconMenuSoc){iconMenuSoc.addEventListener("click",function(e){iconMenu.classList.remove('_active');menuBody.classList.remove('_active');iconMenuSoc.classList.toggle('_active');menuSocBody.classList.toggle('_active')})};function closeMenuOnSkroll(){const menu=document.querySelectorAll('.menu__icon,.menu__body,.menu-soc__icon,.menu-soc__body');menu.forEach((item)=>{item.classList.remove('_active')})}}catch(e){console.log("Error in block:");console.log("Burger menu");console.log(e)}
try{const menuLinks=document.querySelectorAll('[data-goto]');const iconMenu=document.querySelector('.menu__icon');const menuBody=document.querySelector('.menu__body');if(menuLinks.length>0){menuLinks.forEach(menuLink=>{menuLink.addEventListener("click",onMenuLinkClick)});function onMenuLinkClick(e){const menuLink=e.target;if(menuLink.dataset.goto&&document.querySelector(menuLink.dataset.goto)){const gotoBlock=document.querySelector(menuLink.dataset.goto);let gotoBlockValue=gotoBlock.getBoundingClientRect().top+pageYOffset;if(document.querySelector('header').getBoundingClientRect().y==0){gotoBlockValue=gotoBlockValue-65}
if(iconMenu.classList.contains('_active')){document.body.classList.remove('_lock')
iconMenu.classList.remove('_active');menuBoby.classList.remove('_active')}
window.scrollTo({top:gotoBlockValue,behavior:"smooth"});e.preventDefault()}}}}catch(e){console.log("Error in block:");console.log("Skroll link");console.log(e)}
try{const goTop=document.querySelector('._go-top');if(goTop){goTop.addEventListener("click",goToTop);function goToTop(e){window.scrollTo({top:0,behavior:"smooth"});e.preventDefault()}}}catch(e){console.log("Error in block:");console.log("Skroll to top link");console.log(e)}
try{const header=document.querySelector('.header');function onTopHeaderСhecking(){if(pageYOffset==0){header.classList.add('_onTop')}else{header.classList.remove('_onTop')}}
onTopHeaderСhecking()}catch(e){console.log("Error in block:");console.log("Transform header on top");console.log(e)}
try{const goTopLink=document.querySelector('.go-top-link');function toTopBtnHide(){if(pageYOffset>=500){goTopLink.classList.remove('_hide')}else if(pageYOffset<=300){goTopLink.classList.add('_hide')}}}catch(e){console.log("Error in block:");console.log("Fixed go top button");console.log(e)}
try{document.querySelectorAll('.tabs').forEach((parent)=>{parent.querySelectorAll('.tabs__link').forEach((item)=>{item.addEventListener('click',function(e){e.preventDefault();parent.querySelectorAll('.tabs__link').forEach((link)=>{link.classList.remove('_active')});item.classList.add('_active');const id=item.getAttribute('href').replace('#','');const targetTab=parent.querySelector(`#${id}`);parent.querySelectorAll('.tabs__item').forEach((tab)=>{tab.classList.remove('_active')});targetTab.classList.add('_active')})});const first=parent.querySelector('.tabs__link._active');if(first){first.click()}else{parent.querySelector('.tabs__link').click()}})}catch(e){console.log("Error in block:");console.log("Tabs");console.log(e)}
try{const swiperTestimonials=new Swiper('.section-testimonials__slider',{direction:'horizontal',loop:!0,speed:500,effect:'slider',slidesPerView:1,pagination:{el:'.section-testimonials__pagination',type:'custom',clickable:!0,},navigation:{nextEl:'.section-testimonials__btn-next',prevEl:'.section-testimonials__btn-prev',},autoplay:{delay:4000,},on:{init:function(){const paginationContainer=document.querySelector('.section-testimonials__pagination');const slides=Array.from(this.slides);slides.forEach((slide,index)=>{const avatar=slide.querySelector('.review__avatar');avatar.classList.add('pagination-bullet');avatar.addEventListener('click',()=>{this.slideToLoop(index)});paginationContainer.appendChild(avatar)})},slideChange:function(){const paginationContainer=document.querySelector('.section-testimonials__pagination');const bullets=Array.from(paginationContainer.querySelectorAll('.pagination-bullet'));bullets.forEach((bullet)=>{bullet.classList.remove('_active')});bullets[this.realIndex].classList.add('_active')},},});swiperTestimonials.init()}catch(e){console.log("Error in block:");console.log("section testimonials slider");console.log(e)}
try{const swiperPortfolio=new Swiper('.swiper-portfolio',{direction:'horizontal',loop:!1,speed:500,effect:'slider',slidesPerView:1,spaceBetween:30,navigation:{nextEl:'.swiper-portfolio__btn-next',prevEl:'.swiper-portfolio__btn-prev',},});swiperPortfolio.init();window.onload=function(){setTimeout(()=>{document.querySelector('.popup').classList.remove('_no-display')},100)};const popupOpenBtns=document.querySelectorAll('._popup-open');const popupClouseArea=document.querySelector('.popup__close-area');const popupClouseBtn=document.querySelector('.popup__close-btn');const popupBody=document.querySelector('.popup');const popupWrapper=popupBody.querySelector('.swiper-portfolio-wrapper');const menu=document.querySelectorAll('.menu__icon,.menu__body,.menu-soc__icon,.menu-soc__body');if(popupClouseArea!==null){popupClouseArea.addEventListener("click",popupClouse)};if(popupClouseBtn!==null){popupClouseBtn.addEventListener("click",popupClouse)};popupOpenBtns.forEach((btn)=>{btn.addEventListener("click",function(link){link.preventDefault();const work=link.target.closest(".portfolio__work");if(work){slides=work.querySelectorAll('.work');if(slides){if(slideReplace(slides)){popupOpen()}else{console.log("no slides o show")}}}})});function popupOpen(){menu.forEach((item)=>{item.classList.remove('_active')});popupBody.classList.add('_active');scrollController.disabledScroll()}
function popupClouse(){popupBody.classList.remove('_active');setTimeout(()=>{scrollController.enabledScroll()},300)}
function slideReplace(slides){try{popupWrapper.innerHTML='';if(slides.length>0){slides.forEach((slide)=>{let element=document.createElement("div");element.classList.add("swiper-portfolio-slide","swiper-slide");element.appendChild(slide.cloneNode(!0));popupWrapper.appendChild(element)});swiperPortfolio.update();swiperPortfolio.slideTo(0,0,!1)
return!0};return!1}catch(e){console.log("Error in function:");console.log("slideReplace");console.log(e);return!1}}}catch(e){console.log("Error in block:");console.log("section portfolio");console.log(e)}
try{const portfolio=document.querySelector('.portfolio');const moreBtn=document.querySelector('.section-portfolio__more-btn');const lessBtn=document.querySelector('.section-portfolio__less-btn');const portfolioWorks=portfolio.querySelectorAll('.portfolio__work');const lastWork=portfolioWorks[portfolioWorks.length-1];const btnWrapper=document.querySelector('.section-portfolio__btn-wrapper');isMoreWorksVisible=!1;function moreBtnHide(){if(lastWork.offsetHeight>=30&&!isMoreWorksVisible){btnWrapper.classList.add('_no-display')}else{btnWrapper.classList.remove('_no-display')}}
moreBtnHide();window.addEventListener("resize",moreBtnHide);lessBtn.addEventListener('click',function(e){lessBtn.classList.add('_no-display');moreBtn.classList.remove('_no-display');portfolio.style.gridAutoRows=`0px`;isMoreWorksVisible=!1});moreBtn.addEventListener('click',function(e){moreBtn.classList.add('_no-display');lessBtn.classList.remove('_no-display');portfolio.style.gridAutoRows=`auto`;isMoreWorksVisible=!0})}catch(e){console.log("Error in block:");console.log("Section portfolio: hide works");console.log(e)}
try{const animatedElements=document.querySelectorAll('.animation,.animation-fade');let options={threshold:[0.3]};const observer=new IntersectionObserver((entries)=>{entries.forEach((entry)=>{if(entry.isIntersecting){entry.target.classList.add('_show');observer.unobserve(entry.target)}})},{threshold:[0.5]});animatedElements.forEach((element)=>{observer.observe(element)})}catch(e){console.log("Error in block:");console.log("animation");console.log(e)}
try{window.addEventListener('load',function(){let lazyImages=document.querySelectorAll('img[data-src], source[data-srcset], [data-background]');let scripts=document.querySelectorAll('script[data-src]');if(lazyImages){lazyImages.forEach(function(img){if(img.dataset.src){img.src=img.dataset.src;img.removeAttribute('data-src')}else if(img.dataset.srcset){img.srcset=img.dataset.srcset;img.removeAttribute('data-srcset')}else if(img.dataset.background){img.style.backgroundImage=`url(${img.dataset.background})`;img.removeAttribute('data-background')}})}
if(scripts){scripts.forEach(function(src){let script=document.createElement('script');script.src=src.dataset.src;document.body.appendChild(script)})}})}catch(e){console.log("Error in block:");console.log("lazy load");console.log(e)}
try{const tabLinks=document.querySelectorAll('[data-gotab]');const tabLabels=document.querySelectorAll('.tabs__link');if(tabLinks.length>0){tabLinks.forEach(tabLink=>{tabLink.addEventListener("click",goToTab)});function goToTab(e){e.preventDefault();const tabLink=e.target;const tabs=document.querySelector('.tabs');if(tabLink.dataset.gotab&&tabs){let gotabValue=tabs.getBoundingClientRect().top+pageYOffset;if(document.querySelector('header').getBoundingClientRect().y==0){gotabValue=gotabValue-65}
window.scrollTo({top:gotabValue,behavior:"smooth"});tabLabels.forEach(function(item){if(item.getAttribute('href')==`#${tabLink.dataset.gotab}`){item.click()}})}}}}catch(e){console.log("Error in block:");console.log("Skroll to tab");console.log(e)}
try{document.addEventListener('DOMContentLoaded',function(){const form=document.getElementById('form');form.addEventListener('submit',formSend);async function formSend(e){e.preventDefault();let error=formValidate(form);let formData=new FormData(form);if(error===0){form.classList.add('_sending');let response=await fetch('sendmail.php',{method:'POST',body:formData});if(response.ok){console.log(response);let result=await response.json();console.log(result);alert(result.message);form.reset();form.classList.remove('_sending')}else{alert('Ошибка');form.classList.remove('_sending')}}else{alert('Заполните обязательные поля')}}
function formValidate(form){let error=0;let formReq=document.querySelectorAll('._req');for(let index=0;index<formReq.length;index++){const input=formReq[index];formRemoveError(input);if(input.classList.contains('_email')){if(emailTest(input)){formAddError(input);error++}}else if(input.getAttribute("type")==="checkbox"&&input.checked===!1){formAddError(input);error++}else{if(input.value===''){formAddError(input);error++}}}
return error}
function formAddError(input){input.parentElement.classList.add('_error');input.classList.add('_error')}
function formRemoveError(input){input.parentElement.classList.remove('_error');input.classList.remove('_error')}
function emailTest(input){return!/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,8})+$/.test(input.value)}
const formPreview=document.getElementById('formPreview')})}catch(e){console.log("Error in block:");console.log("sending form");console.log(e)}
console.log("end")